name: Run tests and SCA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      
      - name: dotnet restore
        run: dotnet restore
      
      - name: dotnet build
        run: dotnet build --no-restore
      
      - name: dotnet test
        run: dotnet test --no-build --collect:"XPlat Code Coverage"

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        with:
          reports: '*/**/coverage.cobertura.xml'
          targetdir: coveragereport

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: CoverageReport # Artifact name        
          path: coveragereport # Directory containing files to upload

      - name: install stryker
        run: dotnet tool install -g dotnet-stryker

      - name: run stryker
        run: dotnet stryker
        working-directory: "WebApplication1.Tests"

      - name: Upload mutation report artifact
        uses: actions/upload-artifact@v4.2.0
        with:
          name: MutationReport # Artifact name        
          path: WebApplication1.Tests/StrykerOutput # Directory containing files to upload